"""Verify the toolchain: the typst compiler, and the vendored Fira fonts.

Two independent concerns, pinned two different ways, both recorded in
`template/TOOL-SHAS.txt`.

**typst is not vendored.** It is installed by the operating system's package
manager and found on PATH; what this module pins is its *version*. The version is
not cosmetic: `build/numbering_sim.py` reproduces the numbering behaviour of one
specific release (uncertainty B5, resolved empirically), and a release that
changed that behaviour would not crash — it would put wrong reference numbers in
a finished book. `tests/test_parity.py` is the check that detects a real
divergence; the version check exists to say the toolchain moved *before* anyone
spends a day debugging output.

**The fonts are vendored**, and are pinned by sha256. They are not available as a
package, and `--font-path fonts/` deliberately bypasses system fonts, so a
substitution years from now would silently change every line break on every page.

Idempotent: a font already present with the right hash is left alone. Safe to run
on every session start.

    python -m knowledge_base.ops.bootstrap          # fetch fonts, verify everything
    python -m knowledge_base.ops.bootstrap --check  # verify only, fetch nothing
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
FONTS = ROOT / "fonts"
MANIFEST = ROOT / "template" / "TOOL-SHAS.txt"

# The pin lives in the manifest, which is a reviewable file. This constant only
# seeds a manifest that does not carry one yet.
TYPST_VERSION = "0.15.1"
VERSION_KEY = "typst-version"
_VERSION_RE = re.compile(r"(\d+\.\d+\.\d+)")

FONT_URLS = {
    "FiraSans-Regular.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Regular.ttf",
    "FiraSans-Bold.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Bold.ttf",
    "FiraSans-Italic.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Italic.ttf",
    "FiraSans-BoldItalic.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-BoldItalic.ttf",
    "FiraSans-Black.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Black.ttf",
    "FiraMath-Regular.otf": "https://github.com/firamath/firamath/releases/download/v0.3.4/FiraMath-Regular.otf",
}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# ── the manifest ──────────────────────────────────────────────────────


def read_manifest() -> tuple[str, dict[str, str]]:
    """Return the pinned typst version and the pinned font hashes."""
    version = TYPST_VERSION
    fonts: dict[str, str] = {}
    if not MANIFEST.exists():
        return version, fonts
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        head, rest = line.split(None, 1)
        if head == VERSION_KEY:
            version = rest.strip()
        else:
            fonts[rest.strip()] = head
    return version, fonts


def write_manifest(version: str, fonts: dict[str, str]) -> None:
    """Rewrite the manifest.

    The compiler is pinned by version and never by file hash — it is not a file
    this repository owns. An entry that would turn the pin back into a hash is
    refused rather than written.
    """
    forbidden = sorted(n for n in fonts if n in {"typst", "typst.exe", VERSION_KEY})
    if forbidden:
        raise ValueError(
            f"refusing to record a file hash for the compiler: {forbidden}. "
            "typst is pinned by version; see the header of TOOL-SHAS.txt.")
    lines = [
        "# Toolchain pins. Generated by knowledge_base.ops.bootstrap.",
        "# A mismatch means the toolchain moved — investigate before updating a pin.",
        "#",
        "# typst is verified by VERSION, not by hash: it is no longer vendored. It is",
        "# installed by the system package manager and found on PATH, so there is no",
        "# file here to hash. The version matters because build/numbering_sim.py",
        "# reproduces the numbering behaviour of one specific release, and a release",
        "# that changed it would produce wrong reference numbers rather than an error.",
        "# tests/test_parity.py is the check that detects a real divergence.",
        "#",
        "# The fonts are verified by SHA256 because they are vendored: they are not",
        "# available as a package, and --font-path fonts/ deliberately bypasses system",
        "# fonts, so a substitution would silently change every page.",
        f"{VERSION_KEY} {version}",
    ]
    lines += [f"{digest}  {name}" for name, digest in sorted(fonts.items())]
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="")


# ── typst ─────────────────────────────────────────────────────────────


def find_typst() -> Path | None:
    """The one definition of *which* typst this repository uses.

    On PATH, resolved by the platform's own rules — on Windows `shutil.which`
    finds `typst.exe` without any caller knowing about the extension. Returns
    None when it is not installed.
    """
    found = shutil.which("typst")
    return Path(found) if found else None


def typst_version(exe: Path) -> str:
    """The version `exe` reports, e.g. '0.15.1' out of 'typst 0.15.1 (9dfd3a08)'."""
    r = subprocess.run([str(exe), "--version"], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"`{exe} --version` failed: {(r.stderr or r.stdout).strip()}")
    m = _VERSION_RE.search(r.stdout)
    if not m:
        raise RuntimeError(f"no version in `{exe} --version` output: {r.stdout.strip()!r}")
    return m.group(1)


def verify_typst(required: str) -> tuple[Path | None, list[str]]:
    """Locate typst and check its version. Returns (path, failures)."""
    exe = find_typst()
    if exe is None:
        return None, [
            "typst: not found on PATH\n"
            f"    typst {required} must be installed and on PATH — this repository no\n"
            "    longer vendors it. Install it with the system package manager\n"
            "    (`scoop install typst`, `brew install typst`, `cargo install typst-cli`)\n"
            "    or from https://github.com/typst/typst/releases"
        ]
    try:
        found = typst_version(exe)
    except RuntimeError as e:
        return exe, [f"typst: {e}"]
    if found != required:
        return exe, [
            "typst: version mismatch\n"
            f"    required {required}\n"
            f"    found    {found}   ({exe})\n"
            "    numbering behaviour was verified against the required version, and\n"
            "    build/numbering_sim.py reproduces that version's behaviour. A change\n"
            "    there is not a crash — it is wrong reference numbers in a finished\n"
            "    book. tests/test_parity.py is the check that would detect a real\n"
            f"    divergence: run it, then update the {VERSION_KEY} pin in\n"
            f"    {MANIFEST.relative_to(ROOT).as_posix()} deliberately."
        ]
    return exe, []


# ── fonts ─────────────────────────────────────────────────────────────


def fetch(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=120) as r, dest.open("wb") as fh:
        shutil.copyfileobj(r, fh)


def verify_fonts(expected: dict[str, str], check_only: bool) -> tuple[dict[str, str], list[str]]:
    """Fetch missing fonts unless check_only, then hash them all.

    Returns (observed hashes, failures).
    """
    observed: dict[str, str] = {}
    failures: list[str] = []
    for name, url in FONT_URLS.items():
        path = FONTS / name
        if not path.exists():
            if check_only:
                failures.append(f"{name}: missing")
                continue
            print(f"  fetching {name} …", flush=True)
            fetch(url, path)

        digest = sha256(path)
        observed[name] = digest
        if name in expected and expected[name] != digest:
            failures.append(
                f"{name}: sha256 mismatch\n"
                f"    expected {expected[name]}\n    observed {digest}"
            )
        elif name not in expected:
            print(f"  {name}: no pinned hash — recording {digest[:16]}…")
    return observed, failures


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; fetch nothing")
    args = ap.parse_args(argv)

    required, expected = read_manifest()

    exe, failures = verify_typst(required)
    if exe is not None:
        print(f"  typst: {exe}")

    observed, font_failures = verify_fonts(expected, check_only=args.check)
    failures += font_failures

    if failures:
        print("\nBOOTSTRAP FAILED — the toolchain does not match its pins:")
        for f in failures:
            print(f"  {f}")
        print("\nAn unverified toolchain must not be used for a build.")
        return 1

    if not args.check and observed != expected:
        write_manifest(required, observed)
        print(f"  manifest written: {MANIFEST.relative_to(ROOT).as_posix()}")

    print(f"toolchain ready — typst {required}, {len(FONT_URLS)} fonts, all verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
