"""Vendor the pinned toolchain: the typst binary and the Fira fonts.

Builds must never depend on system state — a font substituted years from now would
silently change every page. Everything is pinned by version and verified by
sha256 against `template/TOOL-SHAS.txt`.

Idempotent: a file already present with the right hash is left alone. Safe to run
on every session start.

    python -m knowledge_base.ops.bootstrap          # fetch and verify
    python -m knowledge_base.ops.bootstrap --check  # verify only, fetch nothing
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
TOOLS = ROOT / "tools"
FONTS = ROOT / "fonts"
MANIFEST = ROOT / "template" / "TOOL-SHAS.txt"

TYPST_VERSION = "0.15.1"
TYPST_TARGET = "x86_64-unknown-linux-musl"
TYPST_URL = (
    f"https://github.com/typst/typst/releases/download/v{TYPST_VERSION}"
    f"/typst-{TYPST_TARGET}.tar.xz"
)

FONT_URLS = {
    "FiraSans-Regular.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Regular.ttf",
    "FiraSans-Bold.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Bold.ttf",
    "FiraSans-Italic.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Italic.ttf",
    "FiraSans-BoldItalic.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-BoldItalic.ttf",
    "FiraSans-Black.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/firasans/FiraSans-Black.ttf",
    "FiraMath-Regular.otf": "https://github.com/firamath/firamath/releases/download/v0.3.4/FiraMath-Regular.otf",
}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_manifest() -> dict[str, str]:
    if not MANIFEST.exists():
        return {}
    out = {}
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        digest, name = line.split(None, 1)
        out[name.strip()] = digest
    return out


def write_manifest(entries: dict[str, str]) -> None:
    lines = [
        "# Pinned toolchain hashes. Generated by knowledge_base.ops.bootstrap.",
        "# A mismatch means the upstream artefact changed — investigate before updating.",
        f"# typst {TYPST_VERSION} ({TYPST_TARGET})",
    ]
    lines += [f"{digest}  {name}" for name, digest in sorted(entries.items())]
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="")


def fetch(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=120) as r, dest.open("wb") as fh:
        shutil.copyfileobj(r, fh)


def fetch_typst(dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as td:
        archive = Path(td) / "typst.tar.xz"
        fetch(TYPST_URL, archive)
        with tarfile.open(archive) as tf:
            member = next(m for m in tf.getmembers() if Path(m.name).name == "typst")
            extracted = Path(td) / "x"
            tf.extract(member, extracted, filter="data")
            shutil.move(str(extracted / member.name), dest)
    dest.chmod(0o755)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; fetch nothing")
    args = ap.parse_args(argv)

    expected = read_manifest()
    observed: dict[str, str] = {}
    failures: list[str] = []

    targets: list[tuple[str, Path, object]] = [("typst", TOOLS / "typst", fetch_typst)]
    targets += [(n, FONTS / n, u) for n, u in FONT_URLS.items()]

    for name, path, source in targets:
        if not path.exists():
            if args.check:
                failures.append(f"{name}: missing")
                continue
            print(f"  fetching {name} …", flush=True)
            if callable(source):
                source(path)
            else:
                fetch(str(source), path)

        digest = sha256(path)
        observed[name] = digest
        if name in expected and expected[name] != digest:
            failures.append(
                f"{name}: sha256 mismatch\n"
                f"    expected {expected[name]}\n    observed {digest}"
            )
        elif name not in expected:
            print(f"  {name}: no pinned hash — recording {digest[:16]}…")

    if failures:
        print("\nBOOTSTRAP FAILED — the vendored toolchain does not match its pins:")
        for f in failures:
            print(f"  {f}")
        print(
            "\nThis is a hard stop (autonomy protocol §3): a required resource could\n"
            "not be obtained in a verified form. Do not proceed with an unpinned build."
        )
        return 1

    if not args.check and observed != expected:
        write_manifest(observed)
        print(f"  manifest written: {MANIFEST.relative_to(ROOT)}")

    print(f"toolchain ready — typst {TYPST_VERSION}, {len(FONT_URLS)} fonts, all verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
